[project]
name = "albahaca"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.3",
    "django-admin-sortable2>=2.3.1",
    "pillow>=12.1.1",
    "prettyconf>=2.3.0",
    "sorl-thumbnail>=13.0.0",
]

[dependency-groups]
dev = [
    "django-browser-reload>=1.21.0",
]

prod = [
    "gunicorn>=25.3.0",
]
