# Generated by Django 6.0.3 on 2026-05-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_options_image_order'),
        ('menu', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='menu_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.item'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(condition=models.Q(('menu_item__isnull', False), ('title__isnull', False), _connector='OR'), name='title_or_menu_item_required'),
        ),
    ]
