# Generated by Django 6.0.3 on 2026-08-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_menu_item_alter_image_title_and_more'),
        ('menu', '0006_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='gallery/images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='image',
            name='menu_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.item', verbose_name='Ítem del menú'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Subido el'),
        ),
    ]
