# Generated by Django 6.0.3 on 2026-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('google_maps_url', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('google_reviews_url', models.URLField()),
                ('timetable', models.TextField()),
            ],
        ),
    ]
