# Generated by Django 6.0.3 on 2026-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='google_maps_embed_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
