# Generated by Django 6.0.3 on 2026-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_info_google_maps_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='google_maps_embed_url',
            field=models.URLField(max_length=512),
        ),
    ]
