# Generated by Django 6.0.3 on 2026-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_info_google_maps_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='google_maps_embed_url',
        ),
        migrations.AddField(
            model_name='info',
            name='google_maps_iframe',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
