# Generated by Django 6.0.3 on 2026-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_info_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='google_place_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
