# Generated by Django 6.0.3 on 2026-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_info_google_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='google_maps_iframe',
        ),
        migrations.RemoveField(
            model_name='info',
            name='google_maps_url',
        ),
        migrations.RemoveField(
            model_name='info',
            name='google_reviews_url',
        ),
    ]
