# Generated by Django 6.0.3 on 2026-05-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_info_google_maps_iframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='social',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
