# Generated by Django 6.0.3 on 2026-05-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_info_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='social',
            field=models.TextField(),
        ),
    ]
