# Generated by Django 6.0.3 on 2026-08-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_vacation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Información de contacto', 'verbose_name_plural': 'Información de contacto'},
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
