# Generated by Django 6.0.3 on 2026-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_info_options_alter_vacation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='info',
            name='country',
            field=models.CharField(max_length=255, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='info',
            name='google_place_id',
            field=models.CharField(max_length=255, verbose_name='ID del lugar en Google'),
        ),
        migrations.AlterField(
            model_name='info',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='info',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='info',
            name='social',
            field=models.TextField(verbose_name='Redes sociales'),
        ),
        migrations.AlterField(
            model_name='info',
            name='state',
            field=models.CharField(max_length=255, verbose_name='Estado o provincia'),
        ),
        migrations.AlterField(
            model_name='info',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Calle y número'),
        ),
        migrations.AlterField(
            model_name='info',
            name='timetable',
            field=models.TextField(verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='Código postal'),
        ),
    ]
