# Generated by Django 6.0.3 on 2026-07-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Código')),
                ('close_reservations_at', models.TimeField(verbose_name='Hora límite para realizar reservas')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['close_reservations_at'],
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Número de asientos')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad de mesas disponibles')),
            ],
            options={
                'verbose_name': 'Tipos de mesa',
                'verbose_name_plural': 'Tipos de mesas',
                'ordering': ['seats'],
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Día de la semana',
                'verbose_name_plural': 'Días de la semana',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.service', verbose_name='Turno asociado')),
            ],
            options={
                'verbose_name': 'Franja horaria',
                'verbose_name_plural': 'Franjas horarias',
                'ordering': ['time'],
                'unique_together': {('time', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('party_size', models.PositiveIntegerField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5'), (6, 'P6')], verbose_name='Número de comensales')),
                ('remarks', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profesional que gestionó la reserva')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tabletype', verbose_name='Tipo de mesa')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.timeslot', verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='available_at',
            field=models.ManyToManyField(related_name='services', to='reservations.weekday', verbose_name='Turno disponible estos días'),
        ),
    ]
