# Generated by Django 6.0.3 on 2026-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveIntegerField(choices=[(1, '1 persona'), (2, '2 personas'), (3, '3 personas'), (4, '4 personas'), (5, '5 personas'), (6, '6 personas')], verbose_name='Número de comensales'),
        ),
    ]
