# Generated by Django 6.0.3 on 2026-08-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_party_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Profesional que gestionó la reserva'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.tabletype', verbose_name='Tipo de mesa'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.timeslot', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='reservations.service', verbose_name='Turno asociado'),
        ),
    ]
