# Generated by Django 6.0.3 on 2026-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_managed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveSmallIntegerField(verbose_name='Número de comensales'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_type',
            field=models.ManyToManyField(related_name='reservations', to='reservations.tabletype', verbose_name='Tipo de mesa'),
        ),
    ]
