# Generated by Django 6.0.3 on 2026-08-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_party_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table_type',
        ),
        migrations.CreateModel(
            name='ReservationTableTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_table_type_details', to='reservations.reservation')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_tabletype_details', to='reservations.tabletype')),
            ],
            options={
                'unique_together': {('reservation', 'table_type')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_types',
            field=models.ManyToManyField(related_name='reservations', through='reservations.ReservationTableTypeDetail', to='reservations.tabletype', verbose_name='Tipos de mesas'),
        ),
    ]
