# Generated by Django 6.0.3 on 2026-08-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_reservation_table_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationtabletypedetail',
            options={'verbose_name': 'Detalle de tipo de mesa de reserva', 'verbose_name_plural': 'Detalles de tipos de mesa de reserva'},
        ),
    ]
