# Generated by Django 6.0.3 on 2026-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletype',
            name='zone',
            field=models.CharField(choices=[('I', 'Interior'), ('T', 'Terraza')], default='I', max_length=2, verbose_name='Zona'),
        ),
    ]
