# Generated by Django 6.0.3 on 2026-08-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_tabletype_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletype',
            name='code',
        ),
    ]
