# Generated by Django 6.0.3 on 2026-08-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_remove_tabletype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletype',
            options={'ordering': ['zone', 'seats'], 'verbose_name': 'Tipos de mesa', 'verbose_name_plural': 'Tipos de mesas'},
        ),
        migrations.RemoveField(
            model_name='tabletype',
            name='name',
        ),
    ]
