# Generated by Django 6.0.3 on 2026-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_tabletype_options_remove_tabletype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada'),
        ),
    ]
