# Generated by Django 6.0.3 on 2026-04-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subitem',
            options={'ordering': ['order'], 'verbose_name': 'SubItem'},
        ),
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='categories/covers/'),
        ),
    ]
