# Generated by Django 6.0.3 on 2026-04-01 17:30

from django.db import migrations
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    Category = apps.get_model('menu', 'Category')
    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()


def undo_fill_slugs(apps, schema_editor):
    Category = apps.get_model('menu', 'Category')
    for category in Category.objects.all():
        category.slug = ''
        category.save()


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0003_category_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slugs, undo_fill_slugs),
    ]
