# Generated by Django 6.0.3 on 2026-08-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order'], 'verbose_name': 'Item del menú', 'verbose_name_plural': 'Items del menú'},
        ),
        migrations.AlterModelOptions(
            name='subitem',
            options={'ordering': ['order'], 'verbose_name': 'Subitem del menú', 'verbose_name_plural': 'Subitems del menú'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='categories/covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='details',
            field=models.CharField(max_length=256, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='menu.item', verbose_name='Item del menú'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precio'),
        ),
    ]
